config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">Zach Sebacher</h3>
      <nav class="nav nav-masthead justify-content-center">
        <%= link_to "Home", root_path, class: "nav-link"%>
        <%= link_to "About Me", about_me_path, class: "nav-link" %>
        <%= link_to "Contact", contact_path, class: "nav-link" %>
        <%= link_to "Blog", blogs_path, class: "nav-link" %>
        <%= link_to "Portfolio", portfolios_path, class: "nav-link" %>
        <%= login_helper("nav-link") %>
      </nav>
    </div>
  </header>

app/views/shared/_blog_header.html.erb
<div class="col-md-8 blog-main">
    <h3 id="blog-page-logo" class="pb-4 mb-4 font-italic border-bottom">
    But I'm Not A Developer
    </h3>
    <p>My blog about me pretending I know how to be a developer</p>
</div>

app/views/shared/_blog_nav.html.erb
<div class="navbar nav-scroller bg-primary">
    <div class="container">
        <nav class="nav blog-nav">
            <%= link_to "Home", root_path, class: "nav-link" %>
            <%= link_to "About Me", about_me_path, class: "nav-link" %>
            <%= link_to "Contact", contact_path, class: "nav-link" %>
            <%= link_to "Blog", blogs_path, class: "nav-link" %>
            <%= link_to "Portfolio", portfolios_path, class: "nav-link" %>
            <%= login_helper "nav-link" %>
        </nav>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner text-center">
    <%= copyright_generator %>
    </div>
</footer>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Portfolio</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>